spring.application.name=prescription-service

server.port=4003
grpc.server.port=9003

spring.kafka.bootstrap-servers=kafka:9092

# ---------------- PRODUCER ----------------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional but recommended
#spring.kafka.producer.acks=all
#spring.kafka.producer.retries=3

# ---------------- CONSUMER ----------------
spring.kafka.consumer.group-id=prescription-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# allow event classes to deserialize
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hms.prescriptionservice.kafka.event

# optional but safer
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.data.mongodb.uri=mongodb://prescription-service-db:27017/prescription-service-db
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG